### PR TITLE
Updated documentation and readme

### PR DESCRIPTION
**Pull request by gnzlbg**
- moved the tuple_cat example into the example directory
- commented the tuple_cat example
- added examples to the doxygen documentation
- added small tutorial sections for metafunctions, metafunction classes,
  type lists, and metafunction composition.
- enabled travis (updated also CMakeLists.txt with -std=c++11)

### CODE REVIEW

**Comment by gnzlbg** [comment]
Build passes under travis: [link](https://travis-ci.org/gnzlbg/meta/builds/49174712).

**Comment by ericniebler** [comment]
Great, thanks!

**Comment by ericniebler** [comment]
BTW, if you get a chance, I would greatly appreciate a similar pull for range-v3. Not high priority.

**Comment by gnzlbg** [comment]
Sorry for the delayed answer. I've been thinking about this a bit and I
don't think I'll have time for it anytime soon (for range-v3 it is a much
larger undertaking compared to meta). I would have time for drafting a 2-3
page std proposal to remove the requirement that begin and end iterators
have to match in range-based for loops (and range-based for loops only).
Mail me if you think it is worth doing.

**Comment by ericniebler** [comment]
> Sorry for the delayed answer. I've been thinking about this a bit and I don't think I'll have time for it anytime soon

This is why I didn't want to fork meta. :-( 

>  I would have time for drafting a 2-3 page std proposal to remove the requirement that begin and end iterators have to match in range-based for loops (and range-based for loops only).

I think it's premature, but it's up to you.

**Comment by gnzlbg** [comment]
On Fri, Feb 6, 2015 at 8:52 PM, Eric Niebler <notifications@github.com>
wrote:

> Sorry for the delayed answer. I've been thinking about this a bit and I
> don't think I'll have time for it anytime soon
>
> This is why I didn't want to fork meta. :-(
>

Wait, you meant a similar pull request _with meta documentation_ to
range-v3? (This is possible).

Or a similar pull request _with range-v3_ documentation?

> I think it's premature, but it's up to you.

I think in your previous ranges paper you give enough evidence that:
- the requirement is unnecessary,
- the proposal would not touch iterator concepts,
- more efficient iterator based libraries can be implemented if the
requirement is lifted,
- Since a future concept-based standard library might follow this approach,
the easier it is for people to both develop and use libraries without this
requirement, the better.

**Comment by gnzlbg** [comment]
A quick draft is here, basically you guys did all the work already in the ranges for the standard library draft.

https://github.com/gnzlbg/range-based-for/blob/master/README.md

**Comment by ericniebler** [comment]
> you meant a similar pull request _with meta documentation_ to
range-v3?

This.

I think that in your previous ranges paper you give enough evidence that:
 - the requirement is unnecessary,
 - more efficient iterator based libraries can be implemented if the
requirement is lifted,
 - a future concept-based, range-based, standard library _might_ follow this approach.

When I presented my proposal to the committee in November, someone suggested just changing range-for then and there. Bjarne felt this was racing ahead and nobody protested. If you want to carry this forward, then go for it, but I expect demand and interest to be low until we get farther along with the ranges TS. I'll even champion it at the meeting if you can't make it.

> https://github.com/gnzlbg/range-based-for/blob/master/README.md

I think this stands a better chance if you do more to motivate it and discuss the pros and cons.

**Pull request merged**
