### PR TITLE
Alternate formulation of and_c that allows gcc5.1 to compile range-v3

### PR DESCRIPTION
**Pull request by CaseyCarter**
Also fix clang-3.7 Travis builds using ericniebler/range-v3@d0ba804f

### CODE REVIEW

**Comment by ericniebler** [comment]
Interesting. What about `meta:: or_c`?

**Comment by CaseyCarter** [comment]
> Interesting. What about `meta:: or_c`?

I don't know of a similar trick for computing `or`, and in any case `meta::or_c` doesn't break range-v3 builds with GCC 5.1 ;)

**Comment by ericniebler** [comment]
I prefer to put the new implementation under an ifdef with a comment that has the URL of the GCC bug it's working around.

**Comment by CaseyCarter** [comment]
Took me a while to find [the PR](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66405), ironically enough it's for this exact line in meta.hpp:

> % g++ -std=c++11 -c zip.ii
...
/home/trippels/range-v3/include/meta/meta.hpp:887:66: internal compiler error: in tsubst, at cp/pt.c:12021
```
                                    integer_sequence<bool, (Bools || true)...>>;
```

**Comment by ericniebler** [comment]
Great, thanks.

**Pull request merged**
